### ISSUE TITLE
Add a "BookStack in the media" page

### ISSUE THREAD

**Issue by ssddanbrown** [BookStackApp/website#103]
List out any:

- YouTube video references
- Podcasts references
- Articles (Probably not installations)

Maybe social media version?

**Comment by npankaj365** [comment]
Hi @ssddanbrown, can I work on this? I have been recently been working with BookStack deployment for my workplace, and find it quite helpful. I would like to contribute to the project and believe I can start from here.

**Comment by ssddanbrown** [comment]
@npankaj365 Sure, go for it! I'd imagine this as another [about page](https://github.com/BookStackApp/website/tree/main/content/about). Don't want any media embeds included, just links to external pages.

**Comment by durgasravani23** [comment]
Hi @ssddanbrown and @npankaj365 

Is this in progress or done? If not started, can I take this up?

**Comment by npankaj365** [comment]
Hi @durgasravani23, 

Sorry I missed it completely. You can start this.

Cheers!

**Comment by ssddanbrown** [comment]
Yeah, I have not touched this either so go ahead. Please do not include any of the [official YouTube](https://www.youtube.com/c/BookStackApp) videos, this should only be third-party reporting.

**Comment by dassudip2001** [comment]
I can work on this issue can you plz help me how to set up the project local environment
