### ISSUE TITLE
Add NearlyFreeSpeech as other hosting options

### ISSUE THREAD

**Issue by nawan95** [BookStackApp/website#116]
I just tried installing BookStack on NearlyFreeSpeech.net and it worked. The procedure is same as the Installation Manual in the documentation. With the exception of needing  to use `.htaccess` to point document root to BookStack `public` folder instead of using Apache VirtualHost. So I think you can add it to the documentation. It would be great if there were more hosting options.

**Comment by ssddanbrown** [comment]
Thanks for advising @nawan95 but I'd only really look to list additional services if I can lead them to bookstack specific guidance provided by that service, Otherwise we'd just end up with a generic and large list of hosting services.
