### ISSUE TITLE
Add a configuration cheatsheet

### ISSUE THREAD

**Issue by axelrindle** [BookStackApp/website#119]
While I love BookStack as a wiki platform, the initial configuration is always very stressful for me. The documentation does indeed contain most of the available `.env` options, but clicking through all of the pages in order to find a specific thing is bad UX in my eyes. Adding a new cheatsheet-like page containing **all** available options would be a great improvement in my eyes.

An example of such a cheatsheet might be taken from the [Gitea Docs](https://docs.gitea.io/en-us/config-cheat-sheet/).

**Comment by ssddanbrown** [comment]
Thanks for the input. I think this kind of come down to opinion though but I'll keep it in mind to see if it becomes a common issue. Personally I think it makes sense to have things categorized, and we have the search to provide some discover-ability. 

We do already have a full listing here: https://github.com/BookStackApp/BookStack/blob/development/.env.example.complete
This would be provided in your install (If installing a file/source based install) and this is references from our default user `.env` file.

I don't really want to add yet another point of maintenance for our options, without sufficient requirement, so I'll therefore close this off.
