### ISSUE TITLE
Social Authentication, Google documentation inaccuracy

### ISSUE THREAD

**Issue by smross** [BookStackApp/website#14]
The section on enabling Google Authentication at https://www.bookstackapp.com/docs/admin/social-auth/ is slightly incomplete. The 'APP_URL' environment variable does not exist by default in the `.env` file. You have to create this. For example, an improved version of Step 9 would be:

> Edit the `.env` file and add a variable for `APP_URL`. Set the `APP_URL` environment variable to be the same domain as you entered in step 7. So, in this example, it will be https://example.com.

I added this variable under the 'environment' section at the top

**Comment by ssddanbrown** [comment]
@smross Thanks for letting me know, Now updated with some examples of the `.env` variables to set.
