### ISSUE TITLE
Document export classess in hacking/customization page

### ISSUE THREAD

**Issue by ssddanbrown** [BookStackApp/website#140]
https://github.com/BookStackApp/BookStack/blob/06b5a83d8f5105fceb5f44458df16a1643d7c890/resources/views/layouts/export.blade.php#L14

**Comment by dassudip2001** [comment]
@ssddanbrown how to fix this issue give me an idea

**Comment by ssddanbrown** [comment]
@dassudip2001 In my original link above I point to standardised class names we have for exports.
This issue is to document these classes on our [hacking/customization](https://www.bookstackapp.com/docs/admin/hacking-bookstack/) page.

If you're not sure about this, it may not be an issue to take on since it requires some understanding of how BookStack is applying these, which requires understanding of the BookStack source code.

**Comment by dassudip2001** [comment]
@ssddanbrown [hacking/customization](https://www.bookstackapp.com/docs/admin/hacking-bookstack/) which section then i can cheange the documentation 


and can I start BookStack?

**Comment by ssddanbrown** [comment]
@dassudip2001 It would be a new section to add.

**Comment by dassudip2001** [comment]
what I should change Some suggestions. and how to add a new section .and what is the new section name?
