### ISSUE TITLE
Document permissions setup

### ISSUE THREAD

**Issue by ssddanbrown** [BookStackApp/website#142]
Basically find a place to add this general guidance somewhere: 

https://gist.github.com/ssddanbrown/f0e6e850e57c419c6541dbe6c8facd4b

**Comment by durgasravani23** [comment]
Hi @ssddanbrown I think this document can be placed under, [Admin documentation --> Set up](https://www.bookstackapp.com/docs/)

It can be a new hyperlink called "Permissions Setup"

Let me know your thoughts on this. If you are okay with it, I can make the changes.

**Comment by ssddanbrown** [comment]
@durgasravani23 Sounds good! Feel free to make the changes 👍

**Comment by durgasravani23** [comment]
@ssddanbrown Please review https://github.com/BookStackApp/website/pull/148

**Comment by ssddanbrown** [comment]
Now added as of #148.
