### ISSUE TITLE
Document REMOTE_USER authentication

### ISSUE THREAD

**Issue by cjs59** [BookStackApp/website#145]
Our BookStack instance does not require public access, so the simplest and most secure option for us is for the Apache webserver to handle SSO, in the same way we already have several other web-based systems. This is supported by BookStack's logical theme system, but I only found this by old bug reports and trial and error. Can this be added to the documentation? The procedure I found that worked was:

- Create a new user with your SSO email address and the Admin role
- Create /opt/bookstack/themes/remote_user/functions.php containing the code from https://github.com/BookStackApp/BookStack/pull/2289#issuecomment-857164663, with $authVarName = 'REMOTE_USER';
- Add "APP_THEME=remote_user" to .env
- Configure the web server to use SSO for the BookStack virtual host

**Comment by ssddanbrown** [comment]
Hi @cjs59,

That functionality is a unsupported hack (That could therefore break on update or may have side affects) so is not something I'd add to the core official documentation and therefore I'll close this off.

I am currently building a specific area of the site to share unsupported hacks like this but that will likely be part of a separate repo, so I may add that customization there once built
