### ISSUE TITLE
Don't Understand Sentence

### ISSUE THREAD

**Issue by danfoxley** [BookStackApp/website#151]
https://github.com/BookStackApp/website/blob/main/content/docs/user/roles-and-permissions.md

"Roles can be assigned to users an admin user editing a user's profile in the "Settings > Users" area of the BookStack interface."

**Comment by ssddanbrown** [comment]
Thanks for reporting @danfoxley! Have addressed in dae20cc62bdd6fe594715596d72bfe6a590eb996.
