### ISSUE TITLE
Feature request: Support mermaid

### ISSUE THREAD

**Issue by f-steff** [BookStackApp/website#154]
This feature request is for two things, related to the Mermaid text-to-graphics renderer. The first has much higher priority than the second.

1. Please support links to real-time rendered images, such as this:
`https://mermaid.ink/img/pako:eNpVjstqw0AMRX9FaNVC_ANeFBq7zSbQQrPzZCFsOTMk80CWCcH2v3ccb1qtxD3nCk3Yxo6xxP4W760lUTjVJkCe96ay4gb1NJyhKN7mAyv4GPgxw_7lEGGwMSUXLq-bv18lqKbjqjGodeG6bKh69r8Cz1A3R0oa0_kvOd3jDB-N-7b5_H9ihXPrs-mp7KloSaAieSq4Q8_iyXX5_WlNDKplzwbLvHYkV4MmLNmjUePPI7RYqoy8wzF1pFw7ugj5LVx-AfLqVWg?type=png`

Note: Many people self-host their Mermaid renderer, so the host part of that URL may change.

2. An optional Mermaid image edit button, pointing to a live mermaid editor, such as https://mermaid.live/

Note: Many people self-host their Mermaid live editor, so the host part of that URL may change.

**Comment by ssddanbrown** [comment]
Hi @f-steff,
This repo is for our webiste, not BookStack itself, so I'm going to close this off.

I think this existing BookStack issue may already somewhat cover your fundamental requested use case:
https://github.com/BookStackApp/BookStack/issues/566

**Comment by f-steff** [comment]
Thanks. Sorry!
