### ISSUE TITLE
When i  use npm ran dev  face this isue

### ISSUE THREAD

**Issue by dassudip2001** [BookStackApp/website#158]
![Screenshot from 2023-07-11 16-24-27](https://github.com/BookStackApp/website/assets/85440350/670fe96b-a328-45a3-a556-a0cc2867b677)

**Comment by ssddanbrown** [comment]
Hi @dassudip2001,
The site is built using hugo, so relies on having [hugo installed](https://gohugo.io/installation/) and available on the command line for our build scripts to work.

**Comment by ssddanbrown** [comment]
Do you have the images downloaded? 
If you go inside an image folder (`static/images/blog-cover-images`) can you see and open images?
If not, you likely need to install and set-up [git-lfs](https://git-lfs.com/) (Can likely install via apt). 

If the images do exist, make sure you have the "extended" version of hugo installed. 
The output of running `hugo version` should include `extended` within the version id.

**Comment by dassudip2001** [comment]
I install everything. also  open the image
![Screenshot from 2023-07-14 20-02-48](https://github.com/BookStackApp/website/assets/85440350/0d55e6fd-c536-4416-b3eb-73e47fbc1c20)
![Screenshot from 2023-07-14 20-00-48](https://github.com/BookStackApp/website/assets/85440350/dcca1d21-13d3-4e99-ac39-6a38e1ce98a6)
![Screenshot from 2023-07-14 20-01-32](https://github.com/BookStackApp/website/assets/85440350/48720967-f8b4-4fba-9d33-41ff12c163fc)

**Comment by ssddanbrown** [comment]
@dassudip2001 Your version of Hugo is over three years old. Could try using a newer version.

**Comment by dassudip2001** [comment]
@ssddanbrown It works fine in my local env thanks 
can I work #140 #103

**Comment by ssddanbrown** [comment]
Cool, I'll therefore close this off.

> can I work https://github.com/BookStackApp/website/issues/140 https://github.com/BookStackApp/website/issues/103

Sure! Just add a note to those to say you're working on it (Like already done on 103). If there's no progress/update after about a month I'd presume you're no longer working on it.
