### ISSUE TITLE
Update .env language in cache and sessions docs

### ISSUE THREAD

**Issue by ssddanbrown** [BookStackApp/website#162]
The [cache and sessions docs](https://github.com/BookStackApp/website/blob/main/content/docs/admin/cache-session-config.md) were written when the default `.env` had a lot more options, so it refers to updating env options that are no long in there by default. This should be updated to add/update language like other parts of our docs.

**Comment by dassudip2001** [comment]
https://github.com/BookStackApp/BookStack/blob/development/.env.example.complete Follow this documentation ?

**Comment by ssddanbrown** [comment]
@dassudip2001 I'm not sure what you mean, this is just about tweaking the existing wording to suite the current scenario, where options may not be in the `.env` by default.

**Comment by dassudip2001** [comment]
@ssddanbrown ok .

I was thinking of making some changes. ok then
