### ISSUE TITLE
Translations of docs

### ISSUE THREAD

**Issue by NilsKrause** [BookStackApp/website#166]
Hey @ssddanbrown ,
before I begin I'd like to say: thanks for creating bookstack, it's a great software!
Also like bookstack itself, the website is super! It's simple and has all information setup in a logical, easy to navigate, pattern.

Similarly to bookstack itself that is translated into many different languages already, it would be nice to have the docs translated or at least be translatable as well.
Looking into [hugo](https://gohugo.io/methods/site/languages/) it doesn't seem like a huge task to set it up. I just wanted to check if that even is a path that you would consider. And if so if you would have any specific requirements for the implementation.

I would offer to create a german translation of the docs.

**Comment by ssddanbrown** [comment]
Thanks for offering translations @NilsKrause but I'm not sure I'd want to go down this path.
When it comes to the docs I have to make sure the details we're providing are current and accurate, and that maintaining the site remains a reasonable effort. I'm not convinced I can accomplish those goals if we expand the scope of the site to more languages. In addition, I can only provide support in English.

**Comment by NilsKrause** [comment]
Thanks for the honesty! 
I was almost expecting a response in that direction and can absolutely understand the reasoning.

Then my followup question would be if it would be in your interest if there would be a "self translatable" documentation repository - so either standalone/self hostable (kind like this repo, but with just the documentation) or packaged together with bookstack? So the responsibility to keep the translated docs updated would be on the site of the person hosting the instance.

So to be clear, the key docs I am talking about are the "user docs" not the "admin docs" nor the other content of the site itself.

Maybe let me explain a bit why I'd be interested in something like that. I host a bookstack instance for a few people that are all relatively bad english speakers. The administration is my part, so reading the admin docs in english is no problem, but for the users a german documentation of the features would be really nice, I even started to do a few basic german docs, but I thought that it would be useful for more people than me.

**Comment by ssddanbrown** [comment]
Thanks for the understanding!

> Then my followup question would be if it would be in your interest if there would be a "self translatable" documentation repository

From my view I wouldn't want to expand the scope of what we already support in our official repos.
As soon as we start including things, there's an inherent responsibility on us to maintain and support that. 

As an alternative, I think it would be quite a fun task to build a [BookStack API script](https://github.com/BookStackApp/api-scripts) which takes our website user docs, runs them through a translation API, then insert that into BookStack as a Book.  This could then be ran to generate a base translated variation which you could then take on from there and edit/maintain within your own BookStack instance.

Does that alternative sound like it'd be useful and cover the scenario you have?

**Comment by NilsKrause** [comment]
That actually sounds like a great solution for the problem, with minimal effort.

I will take a look on how to implement it. Thanks for the input. I think the issue here can be closed then, but I will post an update as soon as I have something presentable.

**Comment by ssddanbrown** [comment]
Okay, I'll therefore close this off but please feel free to ask for help/guidance if needed (Either here or the BookStack discord).
