### ISSUE TITLE
Use BookStack for docs

### ISSUE THREAD

**Issue by cgsmith** [BookStackApp/website#168]
It would be nice to use BookStack for the official https://www.bookstackapp.com/docs/

I understand the appeal of using something like Hugo but the better way would be to "eat your own dog food" so to speak. This will in turn lead to a better product.

**Comment by ssddanbrown** [comment]
Hi @cgsmith,
I've previously discussed this in this thread: https://github.com/BookStackApp/BookStack/issues/3386
My thoughts now remain much the same as then.
