### ISSUE TITLE
Missing "themes/" in "Backup and Restore" documentation

### ISSUE THREAD

**Issue by LeoZieger** [BookStackApp/website#176]
In the section "Backup and Restore", the folders that are recommended to backup are

- ` .env`
- `public/uploads`
- `storage/uploads`
- `themes`

(https://www.bookstackapp.com/docs/admin/backup-restore/)

However, the command that is listed to backup all these files/folders does not contain the `themes` folder:

`tar -czvf bookstack-files-backup.tar.gz .env public/uploads storage/uploads`

Is there a reason why this folder is excluded/should not be backup-ed?
In the CLI-backup-option, the `themes ` folder is included in the backup ` .zip` file, so it looks like it is just missing in the manual `tar` command.

**Comment by ssddanbrown** [comment]
Thanks for reporting @LeoZieger, well spotted!
I've just addressed this in 189e1d2b30e2f8077ea7aa23a34305fc10171343.
