### ISSUE TITLE
Update facebook instructions on third party authentication page

### ISSUE THREAD

**Issue by lieszkol** [BookStackApp/website#23]
Step 6 under "Facebook" should read:

6. ~~Enter your base BookStack URL again into the 'Valid OAuth redirect URIs' input and save.~~ Enter the following urls under 'Valid OAuth redirect URIs' and save, changing https://example.com to your own domain where BookStack is hosted:
https://example.com/login/service/facebook/callback
https://example.com/register/service/facebook/callback

**Comment by ssddanbrown** [comment]
Thanks for reporting this issue @lieszkol
