### ISSUE TITLE
Azure AD Authentication instructions

### ISSUE THREAD

**Issue by MacChuck** [BookStackApp/website#24]
Not sure if it was a library change or a Microsoft change, looks like the instructions for Azure AD auth don't work in v0.22.0.

3: Enter a name (‘BookStack’). Keep the ‘Application type’ as ‘Web app / API’. Set the ‘Sign-on URL’ to be ~~the main URL~~ to your BookStack instance.

Main url should be changed to http://example.com/login/service/azure/callback

**Comment by ssddanbrown** [comment]
Thanks for pointing this out @MacChuck. Now fixedx
