### ISSUE TITLE
Conect BookStack to wordpress and woocomerce.

### ISSUE THREAD

**Issue by LoicShmit** [BookStackApp/website#25]
Hello .

It's possible to connect Bookstack and woocomerce ? If the user buy a products in my website, via the plugin woocomer, he have an acces to the documentation link at the products ?

Thanks,
Loic

**Comment by ssddanbrown** [comment]
Sorry for my very late reply but unfortunately the answer is no, There's not way to connect the two in an automated manner unless you're simply provide a user with links to BookStack pages.
There's likely to be better alternative platforms for what you're trying to achieve here.
