### ISSUE TITLE
Propose installing without dev-dependencies for production

### ISSUE THREAD

**Issue by Reflic** [BookStackApp/website#35]
I just noticed that in the documentation aswell as in the scripts `composer install` is executed. For a non-development environment i think it would be better to propose the --no-dev switch, which will skip every package that is listed in the dev-dependencies section. The composer.lock file would still be used as source for the package versions.

I just tested this, with the current release and everything went well.

**Comment by qligier** [comment]
[The doc](https://www.bookstackapp.com/docs/admin/updates/) uses now the --no-dev switch, but (at least) one of the dev dependencies is needed: Barryvdh\Debugbar\ServiceProvider is included in Application.php:679 (package barryvdh/laravel-debugbar).

Not sure if it's an error in the code to have this as requirement or if the doc should just be updated to remove the switch.

**Comment by ssddanbrown** [comment]
@qligier DebugBar should not be needed for production use. At what point or process did you see that error message?

**Comment by qligier** [comment]
When running the composer update:
```bash
# quentin at unicorn-www in /var/www/wiki/BookStack on git:release
→ composer install --no-dev              
> @php -r "!file_exists('bootstrap/cache/services.php') || @unlink('bootstrap/cache/services.php');"
> @php -r "!file_exists('bootstrap/cache/compiled.php') || @unlink('bootstrap/cache/compiled.php');"
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In Application.php line 679:
                                                       
  Class 'Barryvdh\Debugbar\ServiceProvider' not found  
                                                       

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```
or artisan directly:
```bash
# quentin at unicorn-www in /var/www/wiki/BookStack on git:release
→ php artisan view:clear

In Application.php line 679:
                                                       
  Class 'Barryvdh\Debugbar\ServiceProvider' not found 
```

Before that, I only did a `git reset --hard origin/release` to update.

**Comment by ssddanbrown** [comment]
@qligier I'm guessing the DebugBar package is cached as a discovered service. This could happen in some scenarios when effectively changing dependencies like this. 

I would imagine, if you were to delete any `.php` files within the bootstrap/cache` folder of your install, then run-run the composer install, you would no longer get this error.

**Comment by qligier** [comment]
Thank you for the info. Removing the _--no-dev_ flag from the `composer install` command did fix it too if I remember correctly.

**Comment by ssddanbrown** [comment]
Both the install and update pages now show `composer install` with the `--no-dev` flag so I will therefore close this off.
