### ISSUE TITLE
Document the use of page links

### ISSUE THREAD

**Issue by ssddanbrown** [BookStackApp/website#4]
As per ssddanbrown/BookStack#94

**Comment by durgasravani23** [comment]
Hi @ssddanbrown 

I think I can contribute to this issue. I read the existing user documentation to see where it fits.

I noticed that [**Reusing page content**](https://www.bookstackapp.com/docs/user/reusing-page-content/) >> **Easily grabbing syntax** section has the content needed for page links. It is just a matter of rephrasing. 

I propose updating the [**Reusing Page Content**](https://www.bookstackapp.com/docs/user/reusing-page-content/) document with the following changes:

1. Update the document title to, **Linking pages & Reusing Page Content**
2. Update the introduction to reflect the need for linking pages.
3. _Easily grabbing the syntax_ section - Split the content under this into two sub sections and update the content.
a. For linking pages
b. For reusing the page content - _Include tags_ section can be merged under this sub section.
4. Forcing content IDs section and text under it remains as it is.

After changes the document structure should look like this:
# Linking pages & Reusing Page Content
> Content
## Easily grabbing the syntax
### For linking pages
> Content
### For reusing the page content
> Add content and _Include tags_ section can be merged under this section.
#### Forcing content IDs
> Content under this section remains as it is.

Let me know your thoughts. 

Cheers,
Sravani

**Comment by ThorsenRune** [comment]
How can one jump to the source which was linked, in case you want to edit the content?
