### ISSUE TITLE
Internal links (to books/pages)

### ISSUE THREAD

**Issue by npelov** [BookStackApp/website#40]
Hi,

We've tried to use few different documentation engines/wikis for internal documentation. They all have one major issue - If you rename a page or move it to other directory (chapter) you loose all links to it. Editing and reorganizing documentation is a nightmare. If a page becomes too big we split it to folders/chapters and we have to manually rewrite every link to this page.

My suggestion would be that the link to a page should be final, non-mutable and should be as short as possible:
https://demo.bookstackapp.com/p/123
or at least
https://demo.bookstackapp.com/b/10/p/123

The link can 301 redirect to the full page URL.

When SEO is needed the full page URL can be used, but I think most search engines get the idea of 301 redirect, so there is no need to risk page change to break the URL.

**Comment by Zenahr** [comment]
Cool idea. I don't get why this issue has been posted inside the website repo and not the official repo instad.

**Comment by npelov** [comment]
Hmm I messed up the reporting. Can it be moved?

**Comment by Zenahr** [comment]
If you didn't mean to open this issue here feel free to `close this issue`. You should be able to see a red button at the bottom of this page. This would be equivalent to `deleting` your issue.

**Comment by ssddanbrown** [comment]
Apologies for my late response, Closing as this repo is for the website only.

Just some notes on this:

- BookStack will attempt resolution of old page URLs using the the revision system. 
- You can already get id-based links to a page by highlighting a line of content on your page, and then copying the link shown in the little pop-over box.
