### ISSUE TITLE
Suggestion: Add a link to the blog RSS

### ISSUE THREAD

**Issue by avnkx** [BookStackApp/website#46]
I shortly discovered BookStack (very nice by the way!) and wanted to be kept up-to-date with its development and releases.
Unfourtunately there was no link for RSS subscription of the blog, so I had to kind of blindly guess it:

https://www.bookstackapp.com/blog/index.xml

Maybe one could provide a link to that on the website in the future?

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @avnkx and sorry for my late reply.

Now added in 8238edcec21637c0a36953a1fcd1a030b7653d12 to the top of the blog post listing page, along with a link for subscribing to email updates.
