### ISSUE TITLE
Suggestion documentation update LDAP_USER_FILTER in docker-compose.yml

### ISSUE THREAD

**Issue by col-panic** [BookStackApp/website#47]
In the LDAP Configuration page, the `LDAP_USER_FILTER=(&(uid=${user}))` parameter is mentioned. I would appreciate a note, that if one embeds this into a `docker-compose.yml` file, it has to be written like this

`LDAP_USER_FILTER=(&(uid=$${user}))` in order to escape the `${user}` variable.

This is documented in https://stackoverflow.com/a/40619627/905817

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @col-panic and sorry for my late reply. I've now added a note to that option, in 8238edcec21637c0a36953a1fcd1a030b7653d12, just in the comment as part of the option list.
