### ISSUE TITLE
Internal link generation not as expected

### ISSUE THREAD

**Issue by surfsnowpro** [BookStackApp/website#51]
I'm new to using BookStack.  I copied over some markdown I had on a github README, but it seems that BookStack generates tags in an unexpected way.  For instance, I create a header with `# Types` and to link to it in my table of contents, I'm using `[Types](#types)`, but this doesn't work.  I did a page inspection and the generated tag seems to be `#bkmrk-types`.  While this isn't a _major_ problem, it does involve updating all of my internal links and is inconsistent with markdown in as far as I know.  I inspected the raw files from your documentation in your website and saw that the markdown you are using uses the traditional `[{text}](#{text})` format.  Should I continue to update all of my links or is this something that is planned to be addressed?
Thanks,
James

**Comment by ssddanbrown** [comment]
Hi @surfsnowpro,

BookStack will prefix all generated ids with `bkmrk` to prevent conflicts and this is not planned to change soon. The BookStack website is built with a different system hence why it does not use the `bkmrk` prefix itself.

I generally follow CommonMark as a Markdown spec for BookStack and as far as I can see that does not yet dictate any standard way of setting ids for elements, The ID generation is something BookStack does itself, no matter if Markdown is used or not.

This repo is specifically for the website wheras this issue really is focused on functionality of the [BookStack platform](https://github.com/BookStackApp/BookStack) itself so I'm going to close this off.
