### ISSUE TITLE
Language Selection for Pages

### ISSUE THREAD

**Issue by DiscoveryOV** [BookStackApp/website#52]
Allow pages to be created with multiple language versions. For instance, if I go to edit a page there should be a section in the right menu where I can choose which language I'd like the page to be in. Then, when viewing the page the actions menu should have a button to select a different language.

This would be exceptionally helpful for organizations with many users of different languages, or for users of products with multiple languages.

The ability to sort by language in search would be useful as well.

**Comment by ssddanbrown** [comment]
Hi @DiscoveryOV, 
This sounds like a request for the BookStack platform itself. This repo is just for the BookStack website therefore I'll close this.

There's an existing issue which I think is requesting the feature you want here: BookStackApp/BookStack/issues/569.
