### ISSUE TITLE
Screenshot copy error

### ISSUE THREAD

**Issue by onlinejul** [BookStackApp/website#54]
Hi again (and sorry to bother once more),

we have random errors when pasting screenshots into an edited page of Bookstack : 

![image](https://user-images.githubusercontent.com/14540206/73662917-edff5e80-469c-11ea-92fa-10b40dda9351.png)

The setup is : 

- Ubuntu 18.04 LTS
- Apache/2.4.29 (Ubuntu)
- PHP 7.2.24-0ubuntu0.18.04.2
- Bookstack version installed with the script : https://www.bookstackapp.com/docs/admin/installation/#ubuntu-1804

.env :

- STORAGE_TYPE=local_secure

php.ini :

- post_max_size = 10M
- upload_max_filesize = 10M

custom headers :

- no changes to the default parameters so 256 MB

ACL :

- we have checked all acl on folders and it all seems correct

I have activated the APP_DEBUG=true but can't seem to find any related logs even in the laravel.log file.

Do you know what other parameters can be checked ?

Thank again.

Cheers,

Julien

**Comment by ssddanbrown** [comment]
Hello,

Hmm, do you only get this when pasting in the image? If you save the image, open the image manager (image icon) then upload through there does it work?

**Comment by onlinejul** [comment]
So after testing, I can't save the image in the image manager either and the error message is related to the size : 

![image](https://user-images.githubusercontent.com/14540206/73721874-7aedfa80-4725-11ea-8bd0-ce7df139c9c7.png)

But as you can see, it's barely heavy : 26 Ko

Do you have a suggestion ?

Cheers,

Julien

**Comment by onlinejul** [comment]
Hi Dan,

have you had the occasion to look into this issue ?

Thank you again.

Julien

**Comment by ssddanbrown** [comment]
Hi @onlinejul,
Have you checked the permissions of the storage folder and everything within?

**Comment by onlinejul** [comment]
Hi Dan,

on the server, according to the doc, il checked the following directories :

![image](https://user-images.githubusercontent.com/14540206/74032499-696e5200-49b4-11ea-88f8-ccd650c642f5.png)

and

![image](https://user-images.githubusercontent.com/14540206/74032554-830f9980-49b4-11ea-9ad7-68264e4485b7.png)

Just so you have a better understanding of the issue :

- Sometimes, the copy/paste works, it has worked on some screenshots,
- When I changed the settings in php.ini to 10M, it seems to have worked for a day.

Do you see anything wrong with the acls ?

Thank you.

Julien

**Comment by onlinejul** [comment]
Hi Dan,

I made some additionnal tests, when the problem occurs, it seems that restarting the apache2 service resolves the issue.

I don't exactly know what happens to apache and when, but at some point, the service looks like it is in a bad state :

![image](https://user-images.githubusercontent.com/14540206/74316565-0c8ae700-4d7a-11ea-896e-83c43e724ff8.png)

Do you have any idea on how to long term solve this ? I will research this error meanwhile.

Sorry for the delay.

Julien

**Comment by ssddanbrown** [comment]
Hi @onlinejul,

_FYI, I don't track issues in this website repo often so, if you want quicker potential support from myself or others I'd recommend opening an issue on https://github.com/BookStackApp/BookStack/issues instead, referencing this one._

Seems like an odd issue. What kind of machine are you running BookStack on? Just wondering if this could be due to restrained available memory on the system.

**Comment by onlinejul** [comment]
Hi Dan,

sorry for the long delay. So the issue has nothing to do with Bookstack, it happened because we had a routine tested on some servers that would remove the files of the /tmp folder each night. Stopping this cron on this server seemed to have stopped the error from happening.

Sorry for the bother.

Cheers,

Julien

**Comment by ssddanbrown** [comment]
@onlinejul No worries, glad you figured it out!
