### ISSUE TITLE
How do we actually change the editor from WYSIWYG to the Markdown Editor?

### ISSUE THREAD

**Issue by Zenahr** [BookStackApp/website#63]
The [docs](https://www.bookstackapp.com/docs/user/markdown-editor/#content) state the following but don't say how the editor can be swapped:

>If you prefer to write in Markdown, the editor in BookStack can be changed at an instance level to use a markdown editor instead of the default WYSIWYG editor. The option to use Markdown is currently not a user setting but a global instance setting due to formatting differences between the two editors.

Where do I have to look to find the setting? I would like to change to the Markdown editor.

**Comment by Zenahr** [comment]
See #64

**Comment by ssddanbrown** [comment]
Closed by #64
