### ISSUE TITLE
SELinux remark in the installation guide

### ISSUE THREAD

**Issue by MorgeMoensch** [BookStackApp/website#68]
Maybe it would be helpful to have some information about SELinux in the installation guide.

**Comment by ssddanbrown** [comment]
Thanks for the suggestion but I don't really want to add a caveats or warnings for various platform-specific considerations/features within the main install instructions as it can easily get overly complex that way. Maybe if this was really commonly raised issue I'd add it somewhere but from what I've seen most users of a distro with SELinux active will generally have SELinux in their mind when it comes to this stuff anwayway.
