### ISSUE TITLE
Did the repository URL change?

### ISSUE THREAD

**Issue by lommes** [BookStackApp/website#8]
I had some issues while upgrading from 0.13.x to 0.14.x because (somehow) my repository pointed to https://github.com/ssddanbrown/BookStack instead of https://github.com/BookStackApp/BookStack and I had to manually change this. 

I think this might be something worth for the docs, when it wasn't my fault choosing the wrong repo in first place.

**Comment by ssddanbrown** [comment]
Hi @lommes, Sorry about this and yeah, It did change back in October. Usually it's not an issue since GitHub redirects the requests but I had created a fork at some point which messed with things. The fork is not deleted but yes, It is a good idea to add this to the update docs.

**Comment by alexmannuk** [comment]
Given that this is now three years old and we're now on v0.29.3, is it still worth adding this or can it just be closed off?

**Comment by ssddanbrown** [comment]
In my failure to action this in the last 4 years, I'll close this off, Since it should be a very very minor subset of the user-base that might still have that old link, and I'm generally careful not to create my own namespace `bookstack` repo anyway.
