### ISSUE TITLE
Documentation clarification about moving books, chapters and pages

### ISSUE THREAD

**Issue by diegopau** [BookStackApp/website#92]
Hi,

Trying to find out how to move a book to a different shelf I landed in this documentation page https://www.bookstackapp.com/docs/user/organising-content/

There it says "Books and chapters can be moved directly to a new chapter or book" but then explains how you can move a page or chapter (there doesn't seem to be a way to move a book, I wish there was).
Should the sentence be changed to "Pages and chapters can be moved directly to a new chapter or book" ?

**Comment by ssddanbrown** [comment]
Thanks for raising @diegopau.

I've now updated this in the docs.
